### ISSUE TITLE
Индикатор загрузки по умолчанию

### ISSUE THREAD

**Issue by nin-jin** [hyoo-ru/sandbox.hyoo.ru#4]
Сейчас используется кастомный индикатор загрузки, я бы предложил использовать стандартный.
Сейчас он не показывается так как рендерер ничего не знает про айфрейм. Предлагаю сделать компонент

```
$mol_frame $mol_view
    dom_name \iframe
    uri \
```

Он при смене uri через $mol_fiber_sync дожидается события onload или onerror и только тогда позволяет рендерингу завершиться. Тогда в процессе загрузки будет показываться стандартный индикатор.

**Comment by timeshift92** [comment]
Изменил на Frame
